CONFIGURATION bcm_default
	
	//Declare aqui as varivaveis globais do projeto
	VAR_GLOBAL
		VEL_RAP    : BOOL ; //BOBINA AVANCO RAPIDO
		VEL_LEN    : BOOL ; //BOBINA AVANCO LENTO
		VEL_REC    : BOOL ; //BOBINA AVANCO RECUO
		PARTIDA    : BOOL; //ED1 BOTAO DE PARTIDA
		VLT        : BOOL; //ED2 SENSOR TROCA VEL
		CAV        : BOOL; //ED3 SENSOR FIM CURSO
		CAR        : BOOL; //ED4 SENSOR REPOUSO
		TEMPO_FURO : UDINT ; //TEMPO DE FURO EM MS
	END_VAR
	
	//Declare aqui as varivaveis globais retentivas do projeto
	VAR_GLOBAL RETAIN

	END_VAR

		TASK T1 (CONTINUOUS, PRIORITY:=1);
		PROGRAM P1 WITH T1 : FURADEIRA_AUTOMATICA;

END_CONFIGURATION  
