CONFIGURATION bcm_default
	
	//Declare aqui as varivaveis globais do projeto
	VAR_GLOBAL
		FORNO:BOOL;         //SD1 ACIONAMENTO DO FORNO1
		BOTAO:BOOL;         //ED1 INICIO DO PROCESSO
		S_TEMPERATURA:WORD; //EA1 SENSOR DE TEMPERATURA
	END_VAR
	
	//Declare aqui as varivaveis globais retentivas do projeto
	VAR_GLOBAL RETAIN

	END_VAR

		TASK T1 (CONTINUOUS, PRIORITY:=1);
		PROGRAM P1 WITH T1 : DESCRITIVA;

END_CONFIGURATION  
