CONFIGURATION bcm_default
	
	//Declare aqui as varivaveis globais do projeto
	VAR_GLOBAL
		VAR2 : INT ;
		ESTADO_ATUAL:UDINT;
		VAR1:DINT;
		VAR3:UDINT;
		TEMPO_CALC_US: REAL;
	END_VAR
	
	//Declare aqui as varivaveis globais retentivas do projeto
	VAR_GLOBAL RETAIN

	END_VAR

		TASK T1 (CONTINUOUS, PRIORITY:=1);
		PROGRAM P1 WITH T1 : DESCRITIVA;

END_CONFIGURATION  
