CONFIGURATION bcm_template
	
	//Declare aqui as varivaveis globais do projeto
	VAR_GLOBAL
		EXEMPLO_GLOBAL:UINT;
		RSEC :UINT;
		RMIN :UINT;
		RHOR :UINT;
		SD1  :BOOL; //Exemplo de variavel para ser mapeada em pontos digitais
		EA1  :WORD; //Exemplo de variavel para ser mapeada em pontos analogicos
	END_VAR
	
	//Declare aqui as varivaveis globais retentivas do projeto
	VAR_GLOBAL RETAIN
		EXEMPLO_RETENTIVA:UINT;
	END_VAR

		TASK T1 (CONTINUOUS, PRIORITY:=1);
		PROGRAM P1 WITH T1 : DESCRITIVA;

END_CONFIGURATION  
